### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by bemofan** [dangermccann/logseq-metrics#1]
Thanks to the powerful plug-ins，but it doesn't work 
![image](https://user-images.githubusercontent.com/67182689/201835521-1666ff1b-451f-4ae3-9c2b-e1b1529f68cd.png)

**Comment by dangermccann** [comment]
Thanks for your interest in the plugin!  The initial version deployed to the Logseq Marketplace had a configuration issue preventing the renderer from showing anything.  This is fixed now, but I think you will need to uninstall the plugin and then reinstall it.  Can you try that and let me know if it works for you?   Sorry about that!

**Comment by dangermccann** [comment]
In my testing, I actually had to exit and restart Logseq after uninstalling the plugin to get Logseq to refresh the plugin configurations from the Marketplace.

**Comment by bemofan** [comment]
Yeah,It,s OK. Thanks.
