### ISSUE TITLE
Can't add new metrics

### ISSUE THREAD

**Issue by dmytrodubinin** [dangermccann/logseq-metrics#12]
When I try to add new metrics data I get a message "CHANGED: Use command palette to add new metric: ⌘+⇧+P or Ctrl+Shift+P". And when I try to use this shortcuts Logseq only change focus. All plugins disabled!
Look into screencast:
[Screencast from 2023-02-12 18-26-06.webm](https://user-images.githubusercontent.com/8066458/218323490-aeb4463b-efde-4976-befa-61c14be37069.webm)

Logseq 0.8.17

**Comment by dmytrodubinin** [comment]
Oh, sorry. Found problem! On Linux shortcut for command palette is `Ctrl+Alt+P`, not `Ctrl+Shift+P`
Please update your text instruction, because it is confusing!

**Comment by dangermccann** [comment]
Thanks for letting me know.  I didn't realize the shortcut is different on Linux.
