### ISSUE TITLE
[Feature Request] - Separate Data Storage Files per Metric Category

### ISSUE THREAD

**Issue by AdeCsesznak** [dangermccann/logseq-metrics#17]
Your plugin is awesome btw!!  

**Request Summary**

I am using IOS Shortcuts to track my habits.  When I trigger a shortcut, it appends a text string to my logseq markdown file. I use your plugin to monitor progress on properties such as ::weight, ::supplements, etc but I can't use the Data Storage because of IOS Shortcut limitations.

By using IOS Shortcuts, I am not able to leverage the full plugin because I am not able to append Data Points to the metrics-plugin-data.md with multiple properties.

I would like to request the option to split up the metrics-plugin-data.md file into multiple files (each representing one property).  With this type of setup, I could append my habits directly to the md page and leverage the full plugin.  

**Use-Case**

<img width="1804" alt="Feature-Request_Logseq-Metrics" src="https://user-images.githubusercontent.com/105519651/231164995-e1e9c1f8-69a7-4193-9284-81fde1fadc26.png">

**Comment by dangermccann** [comment]
Thanks for the feature request!  I think this is definitely doable.  But let me ask – would it be possible to instead have the shortcut append a block to your journal and use block properties to store the metrics you want to track?  The Metrics Plugin allows you to create [Properties Charts](https://github.com/dangermccann/logseq-metrics#properties-charts) from entries in your journal rather than pulling data from the `metrics-plugin-data` page.  Can you give that a try to see if will meet your needs?

**Comment by AdeCsesznak** [comment]
I've been using the Journal pages to append the metrics as you recommended.  I can successfully view the graphs :) However, I'm having trouble with getting the Cards to work.  I'm interested in having a view where I can view the cards of the metrics on the journal pages. 

Here is an example of the card that I can't get to work:

{{renderer :metrics, weight, -, latest}} (KO)
{{renderer :metrics, weight, -, properties-line}} (OK)

Maybe my syntax is incorrect?

Also I really appreciate you reading and responding to my request.  I love your plugin!!!!

**Comment by dangermccann** [comment]
Got it. The cards currently don’t work with data stored in the journal / block properties. There is a similar feature request for the bar graph, so I’ll go ahead and implement support for all visualizations using block properties.

**Comment by AdeCsesznak** [comment]
That would be awesome!  Thank you very much!!

**Comment by dangermccann** [comment]
I'm working on this now.  I hope to have it released soon.

**Comment by dangermccann** [comment]
Implemented in version 0.17.

**Comment by AdeCsesznak** [comment]
Thank you 🙌
