### ISSUE TITLE
Can't get properties visualization to work

### ISSUE THREAD

**Issue by theCalcaholic** [dangermccann/logseq-metrics#19]
For some reason, properties visualization always shows a blank graph for me.

Here's my minimal example:

- I have a property (`happiness`) on two Journal pages:

    ![Screenshot from 2023-07-17 11-24-22](https://github.com/dangermccann/logseq-metrics/assets/6317548/966c2960-6439-4407-aee0-65950c9fdde6)
    ![Screenshot from 2023-07-17 11-25-01](https://github.com/dangermccann/logseq-metrics/assets/6317548/75f3e588-cb50-4043-876f-ca205acde5d8)

- I have a properties chart on another page
    ```
    {{renderer :metrics, happiness, -, properties-line}}
    ```
    however, the result looks like this:
    
    ![Screenshot from 2023-07-17 11-26-21](https://github.com/dangermccann/logseq-metrics/assets/6317548/b11de271-ec6e-40f6-8dbc-4d15f459417f)

**Comment by dangermccann** [comment]
Can you please try `{{renderer :metrics, :happiness, -, properties-line}}`?

Note the colon at the start of `:happiness`

**Comment by theCalcaholic** [comment]
Sorry, I should have mentioned that I tried that too. Unfortunately, I get the same result

**Comment by theCalcaholic** [comment]
Might be a caching issue of sorts :thinking:

**Comment by fwullschleger** [comment]
Unfortunately, this issue still exists for me. This plugin sounds very promising to me, and I would love to get it to work.
In the past, it worked for a short amount of time. Sadly, I cannot remember the versions of logseq or the plugin I was using.

Building it myself would be an option for me as a temporary workaround, but I cannot find any information on how to do that.

Any help is much appreciated.

**Comment by dangermccann** [comment]
If you could open the dev panel (command-option-i on MacOS) and check the Console for any errors or log messages, that would help me debug this. 

You can build the plugin yourself, assuming you're comfortable with git and working in a terminal window.  Run `npm` to download all the dependencies and `yarn build` to build it.  You'll have to uninstall the existing version of the plugin in Logseq, and then add the local version with the "Load unpacked plugin" function on the Plugins dialog.  You will need to have Developer mode enabled in Advanced settings.

**Comment by theCalcaholic** [comment]
@dangermccann You are aware that what you are suggesting is exactly what I did, right?
After building it myself, everything works.

Here are the errors that show up in the dev console when I use the official build:

![image](https://github.com/dangermccann/logseq-metrics/assets/6317548/f0fae302-d526-4442-83cf-0ac599d6605e)

**Comment by dangermccann** [comment]
Thank you for that.  Those stack traces don't look like code in this plugin.  Out of curiosity, what other plugins are you running?  I'm wondering if there is a conflict between my plugin and other one in the Marketplace.

**Comment by fwullschleger** [comment]
As you can see, I have many plugins installed but not many activated.

![image](https://github.com/dangermccann/logseq-metrics/assets/8968620/7227315b-41f9-40d8-8a97-cf4cd310d83b)

**Comment by theCalcaholic** [comment]
> Thank you for that. Those stack traces don't look like code in this plugin. Out of curiosity, what other plugins are you running? I'm wondering if there is a conflict between my plugin and other one in the Marketplace.

Did you see the error `logseq-metrics can not resolve selector target #slot__74hb8n3o`?

**Comment by fwullschleger** [comment]
> > Thank you for that. Those stack traces don't look like code in this plugin. Out of curiosity, what other plugins are you running? I'm wondering if there is a conflict between my plugin and other one in the Marketplace.
> 
> Did you see the error `logseq-metrics can not resolve selector target #slot__74hb8n3o`?

@theCalcaholic Who is this question for?

**Comment by theCalcaholic** [comment]
@fwullschleger  For @dangermccann .

Imho, the quoted error suggests a build-time issue with whatever frontend framework logseq or logseq-metrics uses (some kind of incompatibility, possibly caching-related)

**Comment by theCalcaholic** [comment]
@fwullschleger Could you share the full list of enabled plugins? I have a suspicion what might be the cause of this...

Here's mine:

`~/.logseq/config/plugins.edn`:
```edn
{:logseq-journals-calendar {:version "0.10.5", :repo "xyhp915/logseq-journals-calendar", :effect false, :theme false}
 :logseq-heatmap {:version "v2.4.3", :repo "pengx17/logseq-plugin-heatmap", :effect true, :theme false}
 :logseq-tags {:version "v0.1.2", :repo "gidongkwon/logseq-plugin-tags", :effect false, :theme false}
 :logseq-bullet-threading {:version "v1.1.0", :repo "pengx17/logseq-plugin-bullet-threading", :effect false, :theme false}
 :logseq-todo-master {:version "v1.10.3", :repo "pengx17/logseq-plugin-todo-master", :effect false, :theme false}
 :logseq-link-preview {:version "v2.2.9", :repo "pengx17/logseq-plugin-link-preview", :effect true, :theme false}
 :logseq-move-block {:version "v0.0.13", :repo "vipzhicheng/logseq-plugin-move-block", :effect true, :theme false}
 :logseq-helium-plugin {:version "v.2.1.1", :repo "vyleung/logseq-helium-plugin", :effect true, :theme false}
 :logtools {:version "0.0.5", :repo "cannibalox/logtools", :effect false, :theme false}
 :logseq-banners-plugin {:version "v3.4.5", :repo "yoyurec/logseq-banners-plugin", :effect true, :theme false}
 :logseq-interstitial {:version "0.1.5", :repo "QWxleA/logseq-interstitial-heading-plugin", :effect false, :theme false}
 :logseq-copy-code-plugin {:version "v.1.1.2", :repo "vyleung/logseq-copy-code-plugin", :effect true, :theme false}
 :logseq-pdf-print {:version "v0.0.3", :repo "supery-chen/logseq-plugin-pdf-print", :effect true, :theme false}
 :logseq-todo-exploder {:version "1.0.3", :repo "sawhney17/logseq-todo-exploder", :effect true, :theme false}
 :logseq-plugin-gpt3-openai {:version "v1.1.2", :repo "briansunter/logseq-plugin-gpt3-openai", :effect true, :theme false}
 :logseq-emoji-picker-fork {:version "v0.0.2", :repo "walsvid/logseq-emoji-picker-fork", :effect false, :theme false}
 :logseq-doc {:version "v1.14.1", :repo "sethyuan/logseq-plugin-doc", :effect true, :theme false}
 :logseq-git {:version "v1.5.0", :repo "haydenull/logseq-plugin-git", :effect true, :theme false}
 :logseq-agenda {:version "v2.15.4", :repo "haydenull/logseq-plugin-agenda", :effect true, :theme false}
 :logseq-mark-map {:version "v0.3.17", :repo "vipzhicheng/logseq-plugin-mark-map", :effect false, :theme false}
 :logseq-markdown-table {:version "v1.7.1", :repo "haydenull/logseq-plugin-markdown-table", :effect false, :theme false}
 :logseq-quick-capture {:version "0.0.7", :repo "tankcool/logseq-quick-capture", :effect false, :theme false}
 :logseq-pdf-export-plugin {:version "2.2.8", :repo "sawhney17/logseq-pdf-export", :effect true, :theme false}
 :logseq-laurel-theme {:version "v1.8.8", :repo "pengx17/logseq-laurel-theme", :effect false, :theme true}
 :logseq-bonofix-theme {:version "v3.8.6", :repo "sansui233/logseq-bonofix-theme", :effect false, :theme true}
 :logseq-metrics {:version "0.18", :repo "dangermccann/logseq-metrics", :effect true, :theme false}
 :unfinished-business {:version "0.1.6", :repo "QWxleA/Unfinished-business", :effect false, :theme false}}
```

**Comment by jspille** [comment]
Same issue here.

Windows 11 Pro - 22H2 
Logseq 0.9.14 - Language German - Date Format yyyy-MM-dd EEEE
Plugins: Metrics0.18; 
and: Imgur Uploadv0.0.4; Journals calendarv0.10.10; Bullet Threadingv1.1.4; Random Note1.1.1; Lock Blockv0.0.7; Block to pagev1.3.0; File Managerv1.4.0; Logseq Markmapv0.3.17

Code: {{renderer :metrics, :kilos, Weight Over Time, properties-line}}

I see only an empty rectangular. Nothing else. 

A "quick query" shows all entries as excerpted: {{query (property :kilos)}}

**Comment by dangermccann** [comment]
I'm able to reproduce this error with the 0.18 build.  It occurs in the compressed/optimized build, but when building with the `--no-optimize` flag.  I will attempt to use the source maps to find out where the problem is.

**Comment by dangermccann** [comment]
I fixed the issue by instructing Parcel to [disable scope](https://parceljs.org/features/scope-hoisting/) hoisting in the build.   Please let me know if this is fixed for you folks in the latest release (0.19).

**Comment by jspille** [comment]
Perfect - I can confirm it works.

**Comment by theCalcaholic** [comment]
Yes, v0.19 works without issues. Thanks for the fix!
