### ISSUE TITLE
Render metrics doesn't update in realtime

### ISSUE THREAD

**Issue by dmytrodubinin** [dangermccann/logseq-metrics#2]
First of all, thank you very much for a promising plugin!

When I add new metrics data, rendered metrics doesn't update data in real time. It shows old data.
After restart Logseq, rendered data is actual.
It would be nice if the graph data is updated in real time if the page is open

**Comment by dangermccann** [comment]
I will soon add in an automatic refresh.  Thank you for the feedback.  

The rendered visualization will refresh if you leave the page and return to it.  It will also refresh if you put your cursor on the renerer block and then press enter.  So you do not need to exit Logseq to get it to refresh.

**Comment by dangermccann** [comment]
Fixed in version 0.9.
