### ISSUE TITLE
Feature request: Add 'today' as an argument for custom date ranges in property charts.

### ISSUE THREAD

**Issue by erkcode** [dangermccann/logseq-metrics#20]
When customising date ranges for property charts, I would love to be able to pass 'today' as an argument to the renderer.

That way, I could add journal pages for future dates without stretching my property charts into an unknown future with arbitrary data.

**Comment by dangermccann** [comment]
I like this suggestion.  One clarifying question -- would you want to substitute 'today' with the date of the journal page that the chart is embedded on?  Or would you prefer to substitute the current day?

**Comment by dangermccann** [comment]
Will be available in version 0.21.
