### ISSUE TITLE
Question: can one plot hidden properties? 

### ISSUE THREAD

**Issue by dbbz** [dangermccann/logseq-metrics#21]
Hello, thanks for the great work!
I was wondering, can I plot hidden page properties like `updated-at` and `created-at`? 
The concrete use-case I'm thinking about is getting a sense of the most active projects/pages, with a heatmap for instance. 
Cheers,

**Comment by dangermccann** [comment]
At the moment the properties charts only work for properties of blocks, not of pages.  Sorry.
