### ISSUE TITLE
Specify the number of recent X times or X days to display

### ISSUE THREAD

**Issue by msjsc001** [dangermccann/logseq-metrics#22]
Hello developer, I really enjoy using your plugin. Currently, I need to set the date range every day, which is quite cumbersome.
Could you please add a feature to specify the number of times or days to display?
In other words, when using Properties Chart or Visualize, allow the user to display data for the most recent X times or X days, instead of specifying a date range.

**Comment by dangermccann** [comment]
Good suggestion.  I will work on this next.

**Comment by dangermccann** [comment]
I implemented the ability to specify the past X days in version 0.21.  Supporting the past X times is a bit trickier.  Let me know if this is important to your use case.

**Comment by dangermccann** [comment]
Closing this as complete now that you can specify days in relative terms.
