### ISSUE TITLE
[Feature Request] Use query and block-properties to render the chart.

### ISSUE THREAD

**Issue by WsinGithub** [dangermccann/logseq-metrics#4]
Hi! Thank you for this amazing plugin!

I am wondering if it is possible to render the chart using data from query? 

To be more specific, I have those block in journal:

```markdown
[[2022/11/18]]
- #Health
weight:: 80
diet:: 2000

[[2022/11/19]]
- #Health
weight:: 79
diet:: 2300

[[2022/11/20]]
- #Health
weight:: 81
diet:: 1900
```

And I want to draw the chart using data from block with `#Health` like this:
![image](https://user-images.githubusercontent.com/55137994/202889647-5cf5f83f-818f-42c1-ab4c-989f4a7fea94.png)

**Comment by dangermccann** [comment]
Good suggestion.  I'll try to add this.

**Comment by dangermccann** [comment]
I added this feature into 0.10.  Please update to the latest version and try it out.  Details on the [readme](https://github.com/dangermccann/logseq-metrics#properties-charts).

**Comment by redstreet** [comment]
Nicely done. This is exactly what I came here to ask. Thanks for this feature, and for this great plugin overall!

**Comment by redstreet** [comment]
BTW, this feature wasn't clear to me from the README.md. Perhaps mentioning something like this might help:


> There are two ways to provide the data that this plugin needs to display graphs. One is the built-in "Metrics Add" command, which captures and writes your data into the `metrics-plugin-data` page. The other way is to simply store your own data as Journal properties. Simply add `weight:: 20` to the first bullet of any Journal page, and this  plugin can find and plot those values.

**Comment by redstreet** [comment]
@dangermccann happy to submit a PR for the README if you prefer.
