### ISSUE TITLE
Metric-added value not showing on journal page

### ISSUE THREAD

**Issue by TammoHeeren** [dangermccann/logseq-metrics#5]
This is a great plugin. Thank you for putting it together and providing it to the community. 

I would like to use it to track daily activities. Currently when I enter a value using metric-add it does add it to the dataset, but I have no visualization on the journal page that something was added for that date. It would be great to show the entered value there.

**Comment by dangermccann** [comment]
Great suggestion.  I'm thinking we can have the UI offer a checkbox that would allow the user to choose to add a block to the journal page that summarizes what was added.

**Comment by ntotao** [comment]
also a checkbox in the plugin settings so I can set the journal feedback by default at every input!

**Comment by dangermccann** [comment]
All done!  Implemented in 0.12.
