### ISSUE TITLE
Visualize not working

### ISSUE THREAD

**Issue by Saidelocha** [dangermccann/logseq-metrics#8]
Hi, 

The visualize is not working.
I've used the context menu.

I got this {{renderer :metrics, Sport, Musculation, cumulative-line}}

But then, nothing appears.

Thanks for your work anyway.

**Comment by dangermccann** [comment]
Can you share the contents of the `metrics-plugin-data` page in your graph?  That will help me reproduce the problem so I can fix it.  Thanks in advance.
